import { day, month, date, year, fulldate } from "./Date-Time";

const invoices_data = [
    { 
        id:1, 
        invoice_id: 'Invoice #1',
        address:'1238 Foxlight avenue,ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'request',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:2, 
        invoice_id: 'Invoice #2',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'draft',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],   
    },
    { 
        id:3, 
        invoice_id: 'Invoice #3',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        created_on:'',
        status: 'awaiting payment',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],    
    },
    { 
        id:4, 
        invoice_id: 'Invoice #4',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        created_on:'',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],    
    },
    { 
        id:5, 
        invoice_id: 'Invoice #5',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'open account', 
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:6, 
        invoice_id: 'Invoice #6',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'paid',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],    
    },
    { 
        id:7, 
        invoice_id: 'Invoice #7',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'void',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:8, 
        invoice_id: 'Invoice #8',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'bad debt',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:9, 
        invoice_id: 'Invoice #9',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'archived',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:10, 
        invoice_id: 'Invoice #10',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'paid',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:11, 
        invoice_id: 'Invoice #11',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'void',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:12, 
        invoice_id: 'Invoice #12',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'awaiting payment',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:13, 
        invoice_id: 'Invoice #13',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'open account',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:14, 
        invoice_id: 'Invoice #14',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:15,
        invoice_id: 'Invoice #15',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'paid',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:16, 
        invoice_id: 'Invoice #16',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'archived',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    }, 
    { 
        id:17, 
        invoice_id: 'Invoice #17',
        address:'1238 Foxlight avenue, ontario ON, K2M J6Y',
        title: 'bathroom reno and...',
        amount: '1800000000.00',
        status: 'open account',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },  
];


export default invoices_data;


/* 
{ 
        id:1, 
        invoice_id: 'Invoice #1',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'request',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:2, 
        invoice_id: 'Invoice #2',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'draft',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],   
    },
    { 
        id:3, 
        invoice_id: 'Invoice #3',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        created_on:'',
        status: 'awaiting payment',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],    
    },
    { 
        id:4, 
        invoice_id: 'Invoice #4',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        created_on:'',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],    
    },
    { 
        id:5, 
        invoice_id: 'Invoice #5',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'open account', 
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:6, 
        invoice_id: 'Invoice #6',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'paid',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],    
    },
    { 
        id:7, 
        invoice_id: 'Invoice #7',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'void',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:8, 
        invoice_id: 'Invoice #8',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'bad debt',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:9, 
        invoice_id: 'Invoice #9',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'archived',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:10, 
        invoice_id: 'Invoice #10',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'paid',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:11, 
        invoice_id: 'Invoice #11',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'void',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:12, 
        invoice_id: 'Invoice #12',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'awaiting payment',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:13, 
        invoice_id: 'Invoice #13',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'open account',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:14, 
        invoice_id: 'Invoice #14',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:15,
        invoice_id: 'Invoice #15',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'paid',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:16, 
        invoice_id: 'Invoice #16',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'archived',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    }, 
    { 
        id:16, 
        invoice_id: 'Invoice #17',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'open account',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },  
*/