import { day, month, date, year, fulldate } from "./Date-Time";

const jobs_data = [
    { 
        id:1, 
        job_id: 'Job#1',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1000000000.00',
        status: 'request',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:2, 
        job_id: 'Job#2',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1200000000.00',
        status: 'invoicing req',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:3, 
        job_id: 'Job#3',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1300000000.00',
        status: 'active',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:4, 
        job_id: 'Job#4',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1400000000.00',
        status: 'new',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:5, 
        job_id: 'Job#5',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1500000000.00',
        status: 'unscheduled',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:6, 
        job_id: 'Job#6',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1600000000.00',
        status: 'new',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:7, 
        job_id: 'Job#7',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1700000000.00',
        status: 'on hold',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:8, 
        job_id: 'Job#8',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1800000000.00',
        status: 'canceled',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:9, 
        job_id: 'Job#9',
        address:'1238 Foxlight avenue, nepean, ON, K2M J6Y',
        title: 'bathroom reno ...',
        amount: '1900000000.00',
        status: 'active',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:10, 
        job_id: 'Job#10',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        title: 'bathroom reno ...',
        amount: '2000000000.00',
        status: 'archived',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:11,
        job_id: 'Job#11',
        address:'1238 Foxlight avenue, ontario K2M 9H11',
        title: 'bathroom reno ...',
        amount: '2100000000.00',
        status: 'completed',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },
    { 
        id:12, 
        job_id: 'Job#12',
        address:'1238 Foxlight avenue, ontario K2M 9H11',
        title: 'bathroom reno ...',
        amount: '2200000000.00',
        status: 'archived',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },  
    { 
        id:13, 
        job_id: 'Job#13',
        address:'1238 Foxlight avenue, ontario K2M 9H11',
        title: 'bathroom reno ...',
        amount: '2300000000.00',
        status: 'canceled',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },  
    { 
        id:14, 
        job_id: 'Job#14',
        address:'1238 Foxlight avenue, ontario K2M 9H11',
        title: 'bathroom reno ...',
        amount: '2400000000.00',
        status: 'completed',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],
    },  
];


export default jobs_data;



/* 
team: ['Alysha', 'Jordan', 'Marley'],
*/