import { day, month, date, year, fulldate } from "./Date-Time";

const QuotesDatas = [
    { 
        id:1, 
        quote_no: 'quote #1',
        title: 'Basement repaint ...',
        amount: '1000.00',
        status: 'request',
        created_on:[`Wednesday`,`Nov`, `16`, `2021`],  
    },
    { 
        id:2, 
        quote_no: 'quote #2',
        title: 'bathroom reno...',
        amount: '1200000000.00',
        status: 'draft',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:3, 
        quote_no: 'quote #3',
        title: 'bathroom reno...',
        amount: '1500000000.00',
        status: 'approved',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    
    { 
        id:4, 
        quote_no: 'quote #4',
        title: 'bathroom reno...',
        amount: '1700000000.00',
        status: 'awaiting response',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:5, 
        quote_no: 'quote #5',
        title: 'bathroom reno...',
        amount: '1800000000.00',
        status: 'converted',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:6, 
        quote_no: 'quote #6',
        title: 'bathroom reno...',
        amount: '1900000000.00',
        status: 'declined',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:7, 
        quote_no: 'quote #7',
        title: 'Bathroom rennocation',
        amount: '10000000000.00',
        status: 'request',
        created_on:[`Wednesday`,`December`, `18`, `2021`],  
    },
    { 
        id:8, 
        quote_no: 'quote #8',
        title: 'bathroom reno',
        amount: '385.00',
        status: 'request',
        created_on:[`Wednesday`,`Nov`, `16`, `2021`],  
    },
    { 
        id:9, 
        quote_no: 'quote #9',
        title: 'bathroom reno...',
        amount: '2200000000.00',
        status: 'awaiting response',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:10, 
        quote_no: 'quote #10',
        title: 'bathroom reno...',
        amount: '2800000000.00',
        status: 'draft',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:11, 
        quote_no: 'quote #11',
        title: 'bathroom reno...',
        amount: '3000000000.00',
        status: 'approved',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:12, 
        quote_no: 'quote #12',
        title: 'bathroom reno...',
        amount: '2950.00',
        status: 'declined',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
   
]

export default QuotesDatas;

/* 
{ 
        id:1, 
        quote_no: 'quote #1',
        // client_name: 'Daniel Morgan',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '1400000000.00',
        status: 'request',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:2, 
        quote_no: 'quote #2',
        // client_name: 'Amce Inc',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '1200000000.00',
        status: 'draft',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:3, 
        quote_no: 'quote #3',
        // client_name: 'Mic Smith',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '1500000000.00',
        status: 'approved',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    
    { 
        id:4, 
        quote_no: 'quote #4',
        // client_name: 'James George',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '1700000000.00',
        status: 'awaiting response',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:5, 
        quote_no: 'quote #5',
        // client_name: 'Jhone Doe',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '1800000000.00',
        status: 'converted',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:6, 
        quote_no: 'quote #6',
        // client_name: 'Ellena Aurora',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '1900000000.00',
        status: 'declined',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:7, 
        quote_no: 'quote #7',
        // client_name: 'Jackson Tim',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '2000000000.00',
        status: 'approved',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:8, 
        quote_no: 'quote #8',
        // client_name: 'Borish Emson',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '2100000000.00',
        status: 'declined',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:9, 
        quote_no: 'quote #9',
        // client_name: 'Adam Kyllie',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '2200000000.00',
        status: 'awaiting response',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:10, 
        quote_no: 'quote #10',
        // client_name: 'Nikhill Kumar',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '2800000000.00',
        status: 'draft',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:11, 
        quote_no: 'quote #11',
        // client_name: 'Ibramhim Jackson',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '3000000000.00',
        status: 'approved',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
    { 
        id:12, 
        quote_no: 'quote #12',
        // client_name: 'Tony Blair',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        title: 'bathroom reno and a huge',
        amount: '2950.00',
        status: 'declined',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`],  
    },
*/
                        