import { day, month, date, year, fulldate } from "./Date-Time";

const RequestDatas = [
    { 
        id:1, 
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        status: 'today',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:2, 
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        status: 'new',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:3, 
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        status: 'upcoming',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:4, 
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        status: 'today',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:5, 
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        status: 'new',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:6, 
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        status: 'upcoming',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:7, 
        client_name: 'Jackson Tim and rell big stuff cool name...',
        status: 'unscheduled',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:8, 
        client_name: 'Borish Emson and rell big stuff cool name...',
        status: 'converted',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:9, 
        client_name: 'Adam Kyllie and rell big stuff cool name...',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:10, 
        client_name: 'Nikhill Kumar and rell big stuff cool name...',
        status: 'completed',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:11, 
        client_name: 'Ibramhim Jackson and rell big stuff cool name...',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:12, 
        client_name: 'Tony Blair and rell big stuff cool name...',
        status: 'completed',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
   
]

export default RequestDatas;


/* 
{ 
        id:1, 
        quote_no: 'quote #1',
        title: 'bathroom reno and a huge',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        // address:"",
        amount: '1400000000.00',
        status: 'quote',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:2, 
        quote_no: 'invoice #1',
        title: 'bathroom reno and a huge',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        // address:"",
        amount: '1400000000.00',
        status: 'invoice',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:3, 
        quote_no: 'job #1',
        title: 'bathroom reno and a huge',
        client_name: 'D’s Garden Center and rell big stuff cool name...',
        address:'3256 Foxlight avenue, nepean, ontario K2M 9H10',
        amount: '1500000000.00',
        status: 'job',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:4, 
        quote_no: 'Job #4',
        title: 'bathroom reno and a huge',
        client_name: 'James George',
        address:'9987 Foxlight avenue, nepean, ontario K2M 9H12',
        amount: '1400000000.00',
        status: 'today',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:5, 
        quote_no: 'quote #5',
        title: 'bathroom reno and a huge',
        client_name: 'Jhone Doe',
        address:'1238 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'new',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:6, 
        quote_no: 'quote #6',
        title: 'bathroom reno and a huge',
        client_name: 'Ellena Aurora',
        address:'3455 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'upcoming',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:7, 
        quote_no: 'quote #7',
        title: 'bathroom reno and a huge',
        client_name: 'Jackson Tim',
        address:'7658 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'unscheduled',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:8, 
        quote_no: 'quote #8',
        title: 'bathroom reno and a huge',
        client_name: 'Borish Emson',
        address:'8741 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'converted',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:9, 
        quote_no: 'quote #9',
        title: 'bathroom reno and a huge',
        client_name: 'Adam Kyllie',
        address:'7362 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:10, 
        quote_no: 'quote #10',
        title: 'bathroom reno and a huge',
        client_name: 'Nikhill Kumar',
        address:'9991 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'completed',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:11, 
        quote_no: 'quote #11',
        title: 'bathroom reno and a huge',
        client_name: 'Ibramhim Jackson',
        address:'6572 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'past due',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
    { 
        id:12, 
        quote_no: 'quote #12',
        title: 'bathroom reno and a huge',
        client_name: 'Tony Blair',
        address:'6572 Foxlight avenue, nepean, ontario K2M 9H11',
        amount: '1400000000.00',
        status: 'completed',
        created_on:[`${day}`,`${month}`, `${date}`, `${year}`], 
    },
*/
                        